package formularios;

import daos.LibroDao;
import entidades.Libro;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class LibrosForm extends javax.swing.JInternalFrame {

    public LibrosForm() {
        initComponents();
        pintarTabla();
    }
    
    private Object[][] convertirAFilasDeTabla(List<Libro> libros) {
        Object[][] matriz = new Object[libros.size()][8];

        for (int i = 0; i < libros.size(); i++) {
            Libro libro = libros.get(i);
            matriz[i][0] = libro.getCodigo();
            matriz[i][1] = libro.getTitulo();
            matriz[i][2] = libro.getAutor();
            matriz[i][3] = libro.getNumPag();
            matriz[i][4] = libro.getEditorial();
            matriz[i][5] = libro.getIsbn();
            matriz[i][6] = libro.getAnioPub();
            matriz[i][7] = libro.getUnidadesDisp();
        }

        return matriz;
    }
    
    private void pintarTabla() {
        LibroDao libroDao = new LibroDao();
        
        try {
            List<Libro> libros = libroDao.obtenerLibros();
            Object[][] filasDeTabla = convertirAFilasDeTabla(libros);
            String[] titulosTabla = new String[] {"Codigo", "Titulo", "Autor", 
                "Num Pagina", "Editorial", "ISBN", "Anio Pub", "Unidades Disp"};

            DefaultTableModel model = new DefaultTableModel(filasDeTabla, titulosTabla);
            tblLibros.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibros = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Libros");

        tblLibros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Titulo", "Autor", "Num Pagina", "Editorial", "ISBN", "Anio Pub", "Unidades Disp"
            }
        ));
        jScrollPane1.setViewportView(tblLibros);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnActualizar)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        pintarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLibros;
    // End of variables declaration//GEN-END:variables
}
