package formularios;

import daos.CdDao;
import daos.DvdDao;
import daos.LibroDao;
import daos.MaterialDao;
import daos.PrestamoDao;
import daos.RevistaDao;
import entidades.Cd;
import entidades.Dvd;
import entidades.Libro;
import entidades.Material;
import entidades.Prestamo;
import entidades.Revista;
import entidades.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class PrestamoForm extends javax.swing.JInternalFrame {

    private PrestamoDao prestamoDao;
    private MaterialDao materialDao;
    private LibroDao libroDao;
    private RevistaDao revistaDao;
    private CdDao cdDao;
    private DvdDao dvdDao;
    private Usuario usuario;
    
    public PrestamoForm(Usuario usuario) {
        initComponents();
        this.prestamoDao = new PrestamoDao();
        this.materialDao = new MaterialDao();
        this.libroDao = new LibroDao();
        this.revistaDao = new RevistaDao();
        this.cdDao = new CdDao();
        this.dvdDao = new DvdDao();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnPrestar = new javax.swing.JButton();
        btnDevolver = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dchFechaPrestamo = new com.toedter.calendar.JDateChooser();
        dchFechaDevolucion = new com.toedter.calendar.JDateChooser();
        lblEstado = new javax.swing.JLabel();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Prestamo");

        jLabel1.setText("Codigo:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnPrestar.setText("Prestar");
        btnPrestar.setEnabled(false);
        btnPrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrestarActionPerformed(evt);
            }
        });

        btnDevolver.setText("Devolver");
        btnDevolver.setEnabled(false);
        btnDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDevolverActionPerformed(evt);
            }
        });

        lblMensaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblMensaje.setText(" ");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha Prestamo:");

        jLabel9.setText("Fecha Devolucion:");

        lblEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEstado.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnLimpiar))
                                    .addComponent(dchFechaPrestamo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dchFechaDevolucion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblMensaje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(dchFechaPrestamo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(dchFechaDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDevolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPrestar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblMensaje)
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiar() {
        txtCodigo.setText("");
        dchFechaPrestamo.setDate(null);
        dchFechaDevolucion.setDate(null);
        lblEstado.setText("");
        lblMensaje.setText("");
        btnPrestar.setEnabled(false);
        btnDevolver.setEnabled(false);
    }

    private Object materialExiste(String codigo) {
        
        Object objeto = null;
        
        try {
            if(codigo.startsWith("LIB")) {
                objeto = libroDao.obtenerLibro(codigo);
            } else if(codigo.startsWith("REV")) {
                objeto = revistaDao.obtenerRevista(codigo);
            } else if(codigo.startsWith("CD")) {
                objeto = cdDao.obtenerCd(codigo);
            } else if(codigo.startsWith("DVD")) {
                objeto = dvdDao.obtenerDvd(codigo);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        return objeto;
        
    }
    
    private boolean materialDisponible(Object object) {
        boolean disponible = false;
        
        if(object instanceof Libro libro) {
            disponible = libro.getUnidadesDisp() > 0;
        } else if(object instanceof Revista revista) {
            disponible = revista.getUnidadesDisp() > 0;
        } else if(object instanceof Cd cd) {
            disponible = cd.getUnidadesDisp() > 0;
        } else if(object instanceof Dvd dvd) {
            disponible = dvd.getUnidadesDisp() > 0;
        } 
        
        return disponible;
    }
    
    private void llenarFormulario(Prestamo prestamo) {
        if (prestamo == null) {
           txtCodigo.setText(prestamo.getCodigo());
        } else {
            txtCodigo.setText(prestamo.getCodigo());
            dchFechaPrestamo.setDate(prestamo.getFechaPrestamo());
            dchFechaDevolucion.setDate(prestamo.getFechaDevolucion());
        }
    }
    
    private Prestamo obtenerDesdeFormulario() {
        Prestamo prestamo = null;
        try {
            Material material = materialDao.obtenerMaterial(txtCodigo.getText());
            prestamo = new Prestamo();
            prestamo.setCodigo(txtCodigo.getText());
            prestamo.setIdMaterial(material.getIdMaterial());
            prestamo.setIdUsuario(usuario.getIdUsuario());
            prestamo.setFechaPrestamo(dchFechaPrestamo.getDate());
            prestamo.setFechaDevolucion(dchFechaDevolucion.getDate());
        } catch (Exception e) {
            e.printStackTrace();
        }
        return prestamo;
    }
    
    private void modificarDisponibilidad(String codigo, Integer valor) {
        
        try {
            if(codigo.startsWith("LIB")) {
                Libro libro = libroDao.obtenerLibro(codigo);
                libro.setUnidadesDisp(libro.getUnidadesDisp() + valor);
                libroDao.modificarLibro(libro);
            } else if(codigo.startsWith("REV")) {
                Revista revista = revistaDao.obtenerRevista(codigo);
                revista.setUnidadesDisp(revista.getUnidadesDisp() + valor);
                revistaDao.modificarRevista(revista);
            } else if(codigo.startsWith("CD")) {
                Cd cd = cdDao.obtenerCd(codigo);
                cd.setUnidadesDisp(cd.getUnidadesDisp() + valor);
                cdDao.modificarCd(cd);
            } else if(codigo.startsWith("DVD")) {
                Dvd dvd = dvdDao.obtenerDvd(codigo);
                dvd.setUnidadesDisp(dvd.getUnidadesDisp() + valor);
                dvdDao.modificarDvd(dvd);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    private void btnPrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrestarActionPerformed
        try {
            Prestamo prestamo = obtenerDesdeFormulario();
            prestamoDao.registrarPrestamo(prestamo);
            modificarDisponibilidad(prestamo.getCodigo(), -1);
            limpiar();
            lblMensaje.setText("Material prestado exitosamente!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnPrestarActionPerformed

    private void btnDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDevolverActionPerformed
        try {
            Prestamo prestamo = obtenerDesdeFormulario();
            prestamoDao.eliminarPrestamo(prestamo);
            modificarDisponibilidad(prestamo.getCodigo(), 1);
            limpiar();
            lblMensaje.setText("Material devuelto exitosamente!");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDevolverActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        
        lblMensaje.setText("");
        String codigo = txtCodigo.getText();

        try {
            // Paso 1: Validar si el material existe:
        
            Object material = materialExiste(codigo);
            
            if(material == null) {
                lblEstado.setText("Material no existe");
                return; // aqui termina
            } 
            
            // Paso 2: Validar si el material ya lo tiene prestado
            // Habilitamos el boton de Devolver
            
            Prestamo prestamo = prestamoDao.obtenerPrestamo(codigo, usuario.getIdUsuario());
            if(prestamo != null) {
                lblEstado.setText("Material ya prestado");
                btnDevolver.setEnabled(true);
                llenarFormulario(prestamo);
                return; // aqui termina
            }
            
            // Paso 3: Validar si el material esta disponible:
            
            if(!materialDisponible(material)) {
                lblEstado.setText("Material no disponible");
                return; // aqui termina
            } 
            
            
            // Paso 4: Si llega hasta aqui, significa que esta disponible
            // Habilitamos el boton de Prestar
            
            lblEstado.setText("Material disponible");
            btnPrestar.setEnabled(true);
            
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnBuscarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDevolver;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnPrestar;
    private com.toedter.calendar.JDateChooser dchFechaDevolucion;
    private com.toedter.calendar.JDateChooser dchFechaPrestamo;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
