package formularios;

import entidades.Rol;
import entidades.Usuario;
import javax.swing.JFrame;

public class PrincipalForm extends javax.swing.JFrame {

    private LoginForm loginForm;
    private Usuario usuario;
    
    private PrincipalForm() {
        throw new UnsupportedOperationException("Not supported yet."); 
    }
    
    public PrincipalForm(LoginForm loginForm, Usuario usuario, Rol rol) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.loginForm = loginForm;
        this.usuario = usuario;
        mostrarMenuPorRol(usuario, rol);
    }
    
    private void mostrarMenuPorRol(Usuario usuario, Rol rol) {
        jmAdministrador.setVisible(false);
        jmBibliotecario.setVisible(false);
        jmEstudiante.setVisible(false);
        
        lblUsuarioYRol.setText("Usuario: " + usuario.getUsuario());
        
        if (rol.getNombre().equals("ADMINISTRADOR")) {
            jmAdministrador.setVisible(true);
        } else if (rol.getNombre().equals("BIBLIOTECARIO")) {
            jmBibliotecario.setVisible(true);
        } else if (rol.getNombre().equals("ESTUDIANTE")) {
            jmEstudiante.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsuarioYRol = new javax.swing.JLabel();
        jdpPrincipal = new javax.swing.JDesktopPane();
        menPrincipal = new javax.swing.JMenuBar();
        jmAdministrador = new javax.swing.JMenu();
        jmRoles = new javax.swing.JMenu();
        jmiListarRoles = new javax.swing.JMenuItem();
        jmUsuarios = new javax.swing.JMenu();
        jmiListarUsuarios = new javax.swing.JMenuItem();
        jmiRegModEliUsuarios = new javax.swing.JMenuItem();
        jmBibliotecario = new javax.swing.JMenu();
        jmLibros = new javax.swing.JMenu();
        jmiListarLibros = new javax.swing.JMenuItem();
        jmiRegModEliLibros = new javax.swing.JMenuItem();
        jmRevistas = new javax.swing.JMenu();
        jmiListarRevistas = new javax.swing.JMenuItem();
        jmiRegModEliRevistas = new javax.swing.JMenuItem();
        jmCds = new javax.swing.JMenu();
        jmiListarCds = new javax.swing.JMenuItem();
        jmiRegModEliCds = new javax.swing.JMenuItem();
        jmDvds = new javax.swing.JMenu();
        jmiListarDvds = new javax.swing.JMenuItem();
        jmiRegModEliDvds = new javax.swing.JMenuItem();
        jmEstudiante = new javax.swing.JMenu();
        jmMateriales = new javax.swing.JMenu();
        jmiLibros = new javax.swing.JMenuItem();
        jmiRevistas = new javax.swing.JMenuItem();
        jmiCds = new javax.swing.JMenuItem();
        jmiDvds = new javax.swing.JMenuItem();
        jmPrestamos = new javax.swing.JMenu();
        jmiListarPrestamos = new javax.swing.JMenuItem();
        jmiPreDevPrestamos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mediateca");
        setSize(new java.awt.Dimension(1000, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblUsuarioYRol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUsuarioYRol.setForeground(new java.awt.Color(0, 0, 153));
        lblUsuarioYRol.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsuarioYRol.setText(" ");
        lblUsuarioYRol.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jdpPrincipal.setBackground(java.awt.Color.lightGray);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 537, Short.MAX_VALUE)
        );

        jmAdministrador.setText("Administrador");

        jmRoles.setText("Roles");

        jmiListarRoles.setText("Listar");
        jmiListarRoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarRolesActionPerformed(evt);
            }
        });
        jmRoles.add(jmiListarRoles);

        jmAdministrador.add(jmRoles);

        jmUsuarios.setText("Usuarios");

        jmiListarUsuarios.setText("Listar");
        jmiListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarUsuariosActionPerformed(evt);
            }
        });
        jmUsuarios.add(jmiListarUsuarios);

        jmiRegModEliUsuarios.setText("Registrar/Modificar/Eliminar");
        jmiRegModEliUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliUsuariosActionPerformed(evt);
            }
        });
        jmUsuarios.add(jmiRegModEliUsuarios);

        jmAdministrador.add(jmUsuarios);

        menPrincipal.add(jmAdministrador);

        jmBibliotecario.setText("Bibliotecario");

        jmLibros.setText("Libros");

        jmiListarLibros.setText("Listar");
        jmiListarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarLibrosActionPerformed(evt);
            }
        });
        jmLibros.add(jmiListarLibros);

        jmiRegModEliLibros.setText("Registrar/Modificar/Eliminar");
        jmiRegModEliLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliLibrosActionPerformed(evt);
            }
        });
        jmLibros.add(jmiRegModEliLibros);

        jmBibliotecario.add(jmLibros);

        jmRevistas.setText("Revistas");

        jmiListarRevistas.setText("Listar");
        jmiListarRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarRevistasActionPerformed(evt);
            }
        });
        jmRevistas.add(jmiListarRevistas);

        jmiRegModEliRevistas.setText("Registrar/Modificar/Eliminar");
        jmiRegModEliRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliRevistasActionPerformed(evt);
            }
        });
        jmRevistas.add(jmiRegModEliRevistas);

        jmBibliotecario.add(jmRevistas);

        jmCds.setText("Cds");

        jmiListarCds.setText("Listar");
        jmiListarCds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarCdsActionPerformed(evt);
            }
        });
        jmCds.add(jmiListarCds);

        jmiRegModEliCds.setText("Registrar/Modificar/Eliminar");
        jmiRegModEliCds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliCdsActionPerformed(evt);
            }
        });
        jmCds.add(jmiRegModEliCds);

        jmBibliotecario.add(jmCds);

        jmDvds.setText("Dvds");

        jmiListarDvds.setText("Listar");
        jmiListarDvds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarDvdsActionPerformed(evt);
            }
        });
        jmDvds.add(jmiListarDvds);

        jmiRegModEliDvds.setText("Registrar/Modificar/Eliminar");
        jmiRegModEliDvds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRegModEliDvdsActionPerformed(evt);
            }
        });
        jmDvds.add(jmiRegModEliDvds);

        jmBibliotecario.add(jmDvds);

        menPrincipal.add(jmBibliotecario);

        jmEstudiante.setText("Estudiante");

        jmMateriales.setText("Materiales");

        jmiLibros.setText("Libros");
        jmiLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLibrosActionPerformed(evt);
            }
        });
        jmMateriales.add(jmiLibros);

        jmiRevistas.setText("Revistas");
        jmiRevistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiRevistasActionPerformed(evt);
            }
        });
        jmMateriales.add(jmiRevistas);

        jmiCds.setText("Cds");
        jmiCds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCdsActionPerformed(evt);
            }
        });
        jmMateriales.add(jmiCds);

        jmiDvds.setText("Dvds");
        jmiDvds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiDvdsActionPerformed(evt);
            }
        });
        jmMateriales.add(jmiDvds);

        jmEstudiante.add(jmMateriales);

        jmPrestamos.setText("Prestamos");

        jmiListarPrestamos.setText("Listar");
        jmiListarPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiListarPrestamosActionPerformed(evt);
            }
        });
        jmPrestamos.add(jmiListarPrestamos);

        jmiPreDevPrestamos.setText("Prestar/Devolver");
        jmiPreDevPrestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPreDevPrestamosActionPerformed(evt);
            }
        });
        jmPrestamos.add(jmiPreDevPrestamos);

        jmEstudiante.add(jmPrestamos);

        menPrincipal.add(jmEstudiante);

        setJMenuBar(menPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 698, Short.MAX_VALUE)
                        .addComponent(lblUsuarioYRol, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jdpPrincipal))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblUsuarioYRol)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jdpPrincipal)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        this.loginForm.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        this.loginForm.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void jmiListarRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarRolesActionPerformed
        RolesForm rolesForm = new RolesForm();
        rolesForm.setSize(600, 300);
        jdpPrincipal.add(rolesForm);
        rolesForm.setVisible(true);
    }//GEN-LAST:event_jmiListarRolesActionPerformed

    private void jmiListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarUsuariosActionPerformed
        UsuariosForm usuariosForm = new UsuariosForm();
        usuariosForm.setSize(600, 300);
        jdpPrincipal.add(usuariosForm);
        usuariosForm.setVisible(true);
    }//GEN-LAST:event_jmiListarUsuariosActionPerformed

    private void jmiListarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarLibrosActionPerformed
        LibrosForm librosForm = new LibrosForm();
        librosForm.setSize(800, 300);
        jdpPrincipal.add(librosForm);
        librosForm.setVisible(true);
    }//GEN-LAST:event_jmiListarLibrosActionPerformed

    private void jmiListarRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarRevistasActionPerformed
        RevistasForm revistasForm = new RevistasForm();
        revistasForm.setSize(800, 300);
        jdpPrincipal.add(revistasForm);
        revistasForm.setVisible(true);
    }//GEN-LAST:event_jmiListarRevistasActionPerformed

    private void jmiListarCdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarCdsActionPerformed
        CdsForm cdsForm = new CdsForm();
        cdsForm.setSize(800, 300);
        jdpPrincipal.add(cdsForm);
        cdsForm.setVisible(true);
    }//GEN-LAST:event_jmiListarCdsActionPerformed

    private void jmiListarDvdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarDvdsActionPerformed
        DvdsForm dvdsForm = new DvdsForm();
        dvdsForm.setSize(800, 300);
        jdpPrincipal.add(dvdsForm);
        dvdsForm.setVisible(true);
    }//GEN-LAST:event_jmiListarDvdsActionPerformed

    private void jmiRegModEliLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliLibrosActionPerformed
        LibroForm libroForm = new LibroForm(usuario);
        libroForm.setSize(470, 470);
        jdpPrincipal.add(libroForm);
        libroForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliLibrosActionPerformed

    private void jmiRegModEliRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliRevistasActionPerformed
        RevistaForm revistaForm = new RevistaForm(usuario);
        revistaForm.setSize(470, 400);
        jdpPrincipal.add(revistaForm);
        revistaForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliRevistasActionPerformed

    private void jmiRegModEliCdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliCdsActionPerformed
        CdForm cdForm = new CdForm(usuario);
        cdForm.setSize(470, 470);
        jdpPrincipal.add(cdForm);
        cdForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliCdsActionPerformed

    private void jmiRegModEliDvdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliDvdsActionPerformed
        DvdForm dvdForm = new DvdForm(usuario);
        dvdForm.setSize(470, 400);
        jdpPrincipal.add(dvdForm);
        dvdForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliDvdsActionPerformed

    private void jmiRegModEliUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRegModEliUsuariosActionPerformed
        UsuarioForm usuarioForm = new UsuarioForm();
        usuarioForm.setSize(470, 400);
        jdpPrincipal.add(usuarioForm);
        usuarioForm.setVisible(true);
    }//GEN-LAST:event_jmiRegModEliUsuariosActionPerformed

    private void jmiLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLibrosActionPerformed
        LibrosForm librosForm = new LibrosForm();
        librosForm.setSize(800, 300);
        jdpPrincipal.add(librosForm);
        librosForm.setVisible(true);
    }//GEN-LAST:event_jmiLibrosActionPerformed

    private void jmiRevistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiRevistasActionPerformed
        RevistasForm revistasForm = new RevistasForm();
        revistasForm.setSize(800, 300);
        jdpPrincipal.add(revistasForm);
        revistasForm.setVisible(true);
    }//GEN-LAST:event_jmiRevistasActionPerformed

    private void jmiCdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCdsActionPerformed
        CdsForm cdsForm = new CdsForm();
        cdsForm.setSize(800, 300);
        jdpPrincipal.add(cdsForm);
        cdsForm.setVisible(true);
    }//GEN-LAST:event_jmiCdsActionPerformed

    private void jmiDvdsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiDvdsActionPerformed
        DvdsForm dvdsForm = new DvdsForm();
        dvdsForm.setSize(800, 300);
        jdpPrincipal.add(dvdsForm);
        dvdsForm.setVisible(true);
    }//GEN-LAST:event_jmiDvdsActionPerformed

    private void jmiListarPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiListarPrestamosActionPerformed
        PrestamosForm prestamosForm = new PrestamosForm(usuario);
        prestamosForm.setSize(800, 250);
        jdpPrincipal.add(prestamosForm);
        prestamosForm.setVisible(true);
    }//GEN-LAST:event_jmiListarPrestamosActionPerformed

    private void jmiPreDevPrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPreDevPrestamosActionPerformed
        PrestamoForm prestamoForm = new PrestamoForm(usuario);
        prestamoForm.setSize(520, 300);
        jdpPrincipal.add(prestamoForm);
        prestamoForm.setVisible(true);
    }//GEN-LAST:event_jmiPreDevPrestamosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenu jmAdministrador;
    private javax.swing.JMenu jmBibliotecario;
    private javax.swing.JMenu jmCds;
    private javax.swing.JMenu jmDvds;
    private javax.swing.JMenu jmEstudiante;
    private javax.swing.JMenu jmLibros;
    private javax.swing.JMenu jmMateriales;
    private javax.swing.JMenu jmPrestamos;
    private javax.swing.JMenu jmRevistas;
    private javax.swing.JMenu jmRoles;
    private javax.swing.JMenu jmUsuarios;
    private javax.swing.JMenuItem jmiCds;
    private javax.swing.JMenuItem jmiDvds;
    private javax.swing.JMenuItem jmiLibros;
    private javax.swing.JMenuItem jmiListarCds;
    private javax.swing.JMenuItem jmiListarDvds;
    private javax.swing.JMenuItem jmiListarLibros;
    private javax.swing.JMenuItem jmiListarPrestamos;
    private javax.swing.JMenuItem jmiListarRevistas;
    private javax.swing.JMenuItem jmiListarRoles;
    private javax.swing.JMenuItem jmiListarUsuarios;
    private javax.swing.JMenuItem jmiPreDevPrestamos;
    private javax.swing.JMenuItem jmiRegModEliCds;
    private javax.swing.JMenuItem jmiRegModEliDvds;
    private javax.swing.JMenuItem jmiRegModEliLibros;
    private javax.swing.JMenuItem jmiRegModEliRevistas;
    private javax.swing.JMenuItem jmiRegModEliUsuarios;
    private javax.swing.JMenuItem jmiRevistas;
    private javax.swing.JLabel lblUsuarioYRol;
    private javax.swing.JMenuBar menPrincipal;
    // End of variables declaration//GEN-END:variables
}
